/**
 * Breadcrumb path builder pure function.
 *
 * Walks a LayoutNode tree and produces a Map<nodeId, breadcrumbPath> for
 * every node. Breadcrumbs use arrow format ("Hero > Header > Logo"),
 * skip generic auto-generated Figma layer names, and apply smart truncation
 * for deeply nested paths (5+ segments).
 */

import type { LayoutNode } from '../layout/types';

// ── Exported constants ───────────────────────────────────────────────

/**
 * Pattern matching Figma auto-generated layer names.
 * Matches "Frame 427", "Group", "Vector 55", etc.
 * Does NOT match "Frame Header", "Group Actions" (intentionally named).
 */
export const GENERIC_NAME_PATTERN = /^(Frame|Group|Rectangle|Ellipse|Vector|Section|Instance|Line|Star|Polygon)\s*\d*$/i;

// ── Public API ───────────────────────────────────────────────────────

/**
 * Build a breadcrumb map for all nodes in the given root trees.
 *
 * @param rootNodes - Top-level layout nodes
 * @returns Map of nodeId -> breadcrumb path string
 */
export function buildBreadcrumbMap(rootNodes: LayoutNode[]): Map<string, string> {
  const map = new Map<string, string>();

  for (const root of rootNodes) {
    const pathParts = isGenericName(root.name) ? [] : [root.name];
    walkForBreadcrumbs(root, pathParts, map);
  }

  return map;
}

// ── Internal helpers ─────────────────────────────────────────────────

/**
 * Recursively walk the tree, recording breadcrumbs for each node.
 *
 * For each child:
 * - If the child's name is generic, pass the same ancestor path (skip it)
 * - If the child's name is meaningful, append it to the path
 */
function walkForBreadcrumbs(
  node: LayoutNode,
  ancestorPath: string[],
  map: Map<string, string>,
): void {
  // Record this node's breadcrumb
  map.set(node.id, formatBreadcrumb(ancestorPath));

  if (!node.children) return;

  for (const child of node.children) {
    const childPath = isGenericName(child.name)
      ? ancestorPath // Skip generic names
      : [...ancestorPath, child.name];
    walkForBreadcrumbs(child, childPath, map);
  }
}

/**
 * Format breadcrumb path parts into a display string.
 *
 * - 0 parts: "" (empty)
 * - 1-4 parts: "A > B > C > D" (full)
 * - 5+ parts: "A > ... > D > E" (smart truncation: first + ... + last 2)
 */
function formatBreadcrumb(parts: string[]): string {
  if (parts.length === 0) return '';
  if (parts.length <= 4) return parts.join(' > ');
  // Smart truncation: first > ... > second-to-last > last
  return `${parts[0]} > ... > ${parts[parts.length - 2]} > ${parts[parts.length - 1]}`;
}

/**
 * Test whether a layer name is auto-generated by Figma.
 */
function isGenericName(name: string): boolean {
  return GENERIC_NAME_PATTERN.test(name);
}
